### ISSUE TITLE
Version working with ecto 3

### ISSUE THREAD

**Issue by Razzeee** [elixir-sqlite/sqlite_ecto2#224]
Hey there,

while trying to upgrade to phoenix 1.4 I get these two errors that are related to sqlite_ecto2 not being able to link to the new deps.

```
Failed to use "db_connection" (versions 2.0.0 and 2.0.1) because
  postgrex (version 0.14.0) requires ~> 2.0
  sqlite_ecto2 (versions 2.3.0 and 2.3.1) requires ~> 1.1


Failed to use "ecto" (versions 3.0.0 and 3.0.1) because
  phoenix_ecto (version 4.0.0) requires ~> 3.0
  sqlite_ecto2 (versions 2.3.0 and 2.3.1) requires 2.2.9
```

**Comment by jalcine** [comment]
Just curious about this. Is there a PR I can submit changes to (if it's there - I wouldn't know where to begin tbh).

**Comment by ConnorRigby** [comment]
Unfortunately i haven't really had time to work on it. 
[here](https://github.com/elixir-ecto/db_connection/issues/167) is a thread on updating to DBConnection 2.0
[here](https://github.com/elixir-ecto/ecto/blob/master/CHANGELOG.md#adapter-changes) is a changelog on what is required for Ecto 3

**Comment by jalcine** [comment]
Just now seeing this.

This does look like a bit of work but doable. I'll see if I can start picking at this.

**Comment by ConnorRigby** [comment]
@jalcine If you do get to this, the Ecto 2 branch will probably need to be brought up to the final version of Ecto2 first. This has been in progress [here](https://github.com/elixir-sqlite/sqlite_ecto2/pull/197)

**Comment by DiodonHystrix** [comment]
In case someone is waiting for this to happen, I've been actually working on this.

You can observe the progress here:
https://github.com/DiodonHystrix/sqlite_ecto2/tree/maintenance/ecto-3

Unfortunately, there is a lot to do. Some tests are failing from integrations tests. Some tests are failing from sqlite_ecto2. I had to add some changes to sqlitex (fork). I still need to go through all the commits in DbConnection,Ecto,EctoSql to make sure that nothing is missing. In short: a lot to do, hopefully it will be done within a few weeks.

**Comment by kitplummer** [comment]
Any news on this front?

**Comment by jalcine** [comment]
Not on my end.

**Comment by DiodonHystrix** [comment]
> Any news on this front?

Unfortunately, I had to postpone indefinitely this project.

**Comment by jalcine** [comment]
&gt; &lt; Unfortunately, I had to postpone indefinitely this project.

That happens! I recently have a [bit of time now](https://v2.jacky.wtf/post/999c6013-df42-431e-83d3-dc51d2c06a51) so I think I’ll look into this. It’s also a hard requirement now since I want to upgrade my use of Phoenix.

(Originally published at: https://v2.jacky.wtf/post/f9348b3b-c441-4dfe-980c-9e9dfd335e3f)

**Comment by ityonemo** [comment]
Hey all, I've got a use case for this, so I'd be interested in helping out.  A bit busy right now on Selectrix/Mavis but I'll be doing Recurse Center soon, where I'll work on my use case, so this can be a major priority.  @adamzapasnik do you have any soundbites on handoff from where you left off (does it seem like a straightforward migration? are there any show-stoppers that caused big blocks?)

@jalcine did you make any headway tinkerincg on it?  Also hi!  It looks like you're really physically close, too bad there's SIP or I'd offer to meet up for coffee.

**Comment by jalcine** [comment]
I'm still working on my project's upgrade to Phoenix.

**Comment by ityonemo** [comment]
no worries!  I kinda started poking at it myself the other day.

**Comment by dsignr** [comment]
Following, I run a production system based on this library. It's holding up fine as it is for now, but would love to upgrade to Ecto 3. This project is a huge life saver, thank you for that. Without this library, I would probably re-writing everything from scratch myself which is NOT what I want to do. So, thank you again.

**Comment by jeanparpaillon** [comment]
Any news on this topic? I think I may be able to give a hand. What is the best starting point ?

**Comment by warmwaffles** [comment]
@jeanparpaillon check out https://github.com/elixir-sqlite/sqlite_ecto2/issues/244

I'm currently digging in to this also as I have a need to for elixir to function with sqlite and I want to use ecto.

**Comment by cw789** [comment]
Can be closed? Finally. ♥️ [elixir-sqlite/ecto_sqlite3](https://github.com/elixir-sqlite/ecto_sqlite3)

**Comment by warmwaffles** [comment]
It most definitely can.
