### ISSUE TITLE
UPSERT with ON CONFLICT

### ISSUE THREAD

**Issue by venkatd** [elixir-sqlite/sqlite_ecto2#225]
It looks like as of 3.24, sqlite3 supports ON CONFLICT UPDATE that mimics the postgres syntax: https://www.sqlite.org/lang_UPSERT.html

I saw that https://github.com/mmzeeman/esqlite has updated to 3.24 at least on the master branch.

I'm a newbie to the Ecto internals so if someone is able to point me in the right direction, I can take a stab at implementing this.

UPSERT will be very useful to us so we can treat sqlite as a key-value store.

**Comment by ConnorRigby** [comment]
We follow releases of `esqlite`, so when it is released i will investigate integrating `UPSERT`s with Ecto. 
For what it's worth if you want to take a look, you can add `{:esqlite, github: "mmzeeman/esqlite", override: true, manager: :rebar3}` to your deps.  [this](https://github.com/Sqlite-Ecto/sqlite_ecto2/blob/master/lib/sqlite_ecto/connection.ex#L161) is likely the function that will need to be updated.

**Comment by ConnorRigby** [comment]
and [here](https://github.com/elixir-ecto/ecto_sql/blob/master/lib/ecto/adapters/postgres/connection.ex#L215-L230) is the `postgrex` implementation

**Comment by venkatd** [comment]
@ConnorRigby thanks for the pointers.

**Comment by ConnorRigby** [comment]
Closed by #233
